# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - CABALVER=1.24 GHCVER=8.0.2
 - CABALVER=2.0  GHCVER=8.2.2
 - CABALVER=2.2  GHCVER=8.4.4
 - CABALVER=2.4  GHCVER=8.6.5
 - CABALVER=3.0  GHCVER=8.8.3
 - CABALVER=head GHCVER=head   # see section about GHC HEAD snapshots

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - curl -sSfL https://github.com/summerwind/h2spec/releases/download/v2.3.0/h2spec_linux_amd64.tar.gz | tar -zxC $HOME/bin
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - case $CABALVER in [12].*) cabal install --only-dependencies --enable-tests --enable-benchmarks -f devel;; esac
 - rm -fv cabal.project.local
 - rm -f cabal.project.freeze
 - cabal install hspec-discover

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure --enable-tests --enable-benchmarks -v2 -f devel # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal test
 - cabal check
